# Generated by Django 4.1.5 on 2023-02-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
